### ISSUE TITLE
Dropdown Resizing

### ISSUE THREAD

**Issue by ebidel** [Polymer/paper-dropdown#2]
_From @thisboyiscrazy on November 15, 2014 15:51_

I have a dropdown with content that changes based on another dropdown. The popup part of the drop down is not resizing if the content changes so I end up with a scroll bar.

_Copied from original issue: Polymer/polymer#930_

**Comment by tsega** [comment]
Any progress in solving this issue?

**Comment by omerts** [comment]
Hey morethanreal,

Maybe you can add the height and width reset to core-dropdown's measure function, which runs on every open:
```
measure: function() {
      var target = this.target;
      // remember position, because core-overlay may have set the property
      var pos = target.style.position;

      // get the size of the target as if it's positioned in the top left
      // corner of the screen
      target.style.position = 'fixed';
      target.style.left = '0px';
      target.style.top = '0px';

      /**
       * Reset the explicit width and height of the sizingTarget
       * for cases when content was changed dynamically
       */
      this.sizingTarget.style.height = "";
      this.sizingTarget.style.width = "";

      var rect = target.getBoundingClientRect();

      target.style.position = pos;
      target.style.left = null;
      target.style.top = null;

      return rect;
    },
```

**Comment by omerts** [comment]
There is another problem with dynamic dropdown content. "core-overlay" is watching for changes in the target (our dropdown), and once the target's content changes, core-overlay changes its display to none.
You can find it at core-overlay.html on line 305:
```
    targetChanged: function(old) {
      if (this.target) {
        // really make sure tabIndex is set
        if (this.target.tabIndex < 0) {
          this.target.tabIndex = -1;
        }
        this.addElementListenerList(this.target, this.targetListeners);
        this.target.style.display = 'none';
        this.target.__overlaySetup = false;
      }...
```

**Comment by StephanBeutel** [comment]
+1 
resizing is necessary. Populating the dropdown with new values must trigger a resize.

**Comment by Eugenitals** [comment]
vote!

**Comment by fedy2** [comment]
+1

**Comment by czellweg** [comment]
+1 I would like to see this feature too. I'm working on a dropdown which gets populated based on results returned from an ajax call.
The first time the call returns and the dropdown opens, everything looks fine and it's resized appropriately. However, on subsequent calls - like others have pointed out above - there appears a scrollbar without resizing or (depending on the number of results returned in the first call) the dropdown is too big and fills up unnecessary space on the screen.

**Comment by czellweg** [comment]
The quick-fix suggested by @thisboyiscrazy worked for me:

```javascript
update: function() {
  var self = this; // self points to the polymer input element with the dropdown attached

  // update the model of your dropdown here

  if (self.focused) {
       setTimeout(function() {
          self.$.dropdown.$.scroller.style.height = ""
          self.$.dropdown.$.scroller.style.width = ""
          self.$.dropdown.open();
       }, redrawFix);
   }
}
```

**Comment by morethanreal** [comment]
This should be fixed with https://github.com/Polymer/core-dropdown/commit/921c2b8703d2b03c9e63952937f7a9fda10458a9.

**Comment by dominik0711** [comment]
Still not fixed yet! I have to follow the advice from @czellweg to trigger recalculation of `core-dropdown`. Currently seen in `Polymer v0.5.5`

**Comment by JanMiksovsky** [comment]
If this is still a bug, I'm interested in getting a repro case.

The successor to this component appears to be iron-dropdown, but iron-dropdown appears to resize as expected when new items are added. See http://jsbin.com/xemopu/edit?html,output.

If anyone can offer a repro case with iron-dropdown or another contemporary element (paper-dropdown-menu, paper-menu-button, etc.), please post!
